Repository num-codex/codex-feasibility-backend, pull requests merged in 2022-02, with the labels that each got.

#92 Ensure DSF Can Resolve Site Names
  src/main/java/de/numcodex/feasibility_gui_backend/query/broker/SiteNotFoundException.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFBrokerClient.java
  src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFBrokerClientTest.java
Labels: bug

#88 Fix Race Condition Using Multiple Brokers
  src/main/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerService.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/broker/BrokerClient.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/broker/aktin/AktinBrokerClient.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/broker/aktin/WrappedNotificationListener.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/broker/direct/DirectBrokerClient.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFBrokerClient.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultCollector.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/broker/mock/MockBrokerClient.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/collect/QueryCollectSpringConfig.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/collect/QueryStatusListener.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/collect/QueryStatusListenerImpl.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/collect/QueryStatusUpdate.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/dispatch/QueryDispatcher.java
  src/test/java/de/numcodex/feasibility_gui_backend/query/broker/direct/DirectBrokerClientIT.java
  src/test/java/de/numcodex/feasibility_gui_backend/query/broker/direct/DirectBrokerClientTest.java
  src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultCollectorIT.java
  src/test/java/de/numcodex/feasibility_gui_backend/query/broker/mock/MockBrokerClientIT.java
  src/test/java/de/numcodex/feasibility_gui_backend/query/broker/mock/MockBrokerClientTest.java
  src/test/java/de/numcodex/feasibility_gui_backend/query/collect/QueryStatusListenerImplIT.java
Labels: bug

#82 Add Docker ARM Build
  .github/workflows/ci.yml
Labels: operation

#90 Feature/89 allow for log level adjustments
  README.md
  docker-compose.yml
  src/main/resources/application.yml
Labels: enhancement

#94 Update DSF Dependencies to Version 0.5.4
  pom.xml
Labels: operation

#96 Add Missing JAXB API Dependency
  pom.xml
Labels: bug, operation
